### PR TITLE
Fix wrong output for stack overflow case

### LINKED ISSUE #81: Stack overflow is not properly reported on the website
In the gross store exercises. Using the following code will generate a blank error message on the website:

func GetItem(bill map[string]int, item string) (int, bool) {
    qty , ok := GetItem(bill, item)
    return qty, ok
}

### PR DESCRIPTION
**Pull request by junedev**
Fixes #81

### CODE REVIEW

File: testrunner/execute.go [hunk 1]
```diff
@@ -337,7 +340,7 @@ type config struct {
 func findAdditionalTestFlags(input_dir string) []string {
 	configContent, err := os.ReadFile(filepath.Join(input_dir, ".meta", "config.json"))
 	if err != nil {
-		log.Printf("failed to read config.json: %v", err)
+		log.Printf("warning: config.json could not be read: %v", err)
```
Comment (junedev) [inline testrunner/execute.go:343]: This is not related to the issue, just a minor improvement to make it clear that this is not an error. (The case happens for a lot of the test folders.)

**Review by andrerfcsantos — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
